version: '2'
services:
    myrealtutor-app:
        image: myrealtutor
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://myrealtutor-mariadb:3306/myrealtutor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://myrealtutor-elasticsearch:9200
        ports:
            - 8080:8080
    myrealtutor-mariadb:
        extends:
            file: mariadb.yml
            service: myrealtutor-mariadb
    myrealtutor-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myrealtutor-elasticsearch
